version: '3'
services:
  app:
    container_name: morpheus_connection
    build: .
    tty: true
    ports:
      - '3001:7001'
    volumes:
      - type: bind
        source: .
        target: /morpheus
    networks:
      - my-network
    env_file:
      - .env
networks:
  my-network: